version: '2'
services:
  jenkins-master:
    extends:
      file: common.yml
      service: jenkins-master
    depends_on:
      - "jenkins-slave"
    networks:
      my_net:
        ipv4_address: 172.18.0.2

  jenkins-slave:
    extends:
      file: common.yml
      service: jenkins-slave
    networks:
      my_net:
        ipv4_address: 172.18.0.3

networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16